export interface Product {
  id: number;
  name: string;
  price: string;
  priceRange?: string;
  image: string;
  category: string;
  description: string;
  rating: number;
  reviews: number;
  sku: string;
  tags: string[];
  detailedDescription?: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Cup Holder - PreMade",
    price: "$15.00",
    priceRange: "$15.00 - $25.00",
    image: "/white-cup-holder-with-plant-and-teddy-bear.jpg",
    category: "Cup Holder",
    description: "Eco-friendly, reusable cup holder made from durable fabric — perfect for your daily drinks and sustainable lifestyle.",
    rating: 5,
    reviews: 12,
    sku: "CUP-HLD-PM-01",
    tags: ["Eco-Friendly", "PreMade", "Personalized"],
    detailedDescription: "The Cup Holder is the ideal companion for eco-conscious individuals who love their daily coffee, bubble tea, or smoothies but want to reduce their environmental footprint. Designed to replace single-use plastic bags and carriers, this fabric cup holder promotes sustainability without compromising on style or convenience.",
  },
  {
    id: 2,
    name: "Cup Holder - Red/White",
    price: "$18.00",
    priceRange: "$18.00 - $28.00",
    image: "/red-and-white-cup-holders-with-straps.jpg",
    category: "Cup Holder",
    description: "Stylish red and white cup holder with adjustable straps for all cup sizes.",
    rating: 5,
    reviews: 8,
    sku: "CUP-HLD-RW-02",
    tags: ["Eco-Friendly", "Colorful", "Adjustable"],
    detailedDescription: "Crafted from high-quality, eco-friendly materials, this cup holder is durable, washable, and easy to fold and carry in your bag or pocket.",
  },
  {
    id: 3,
    name: "Cup Holder - Br/Wh",
    price: "$20.00",
    priceRange: "$20.00 - $30.00",
    image: "/brown-and-white-cup-holder-with-strap.jpg",
    category: "Cup Holder",
    description: "Classic brown and white design with premium fabric quality.",
    rating: 5,
    reviews: 15,
    sku: "CUP-HLD-BW-03",
    tags: ["Eco-Friendly", "Classic", "Premium"],
    detailedDescription: "What makes it truly special is the option to personalize: embroider your name, initials, or favorite symbol to create a design that's uniquely yours.",
  },
  {
    id: 4,
    name: "Cup Holder - Smiley",
    price: "$15.00",
    priceRange: "$15.00 - $25.00",
    image: "/colorful-cup-holders-with-smiley-face-and-coffee-d.jpg",
    category: "Cup Holder",
    description: "Fun smiley face design perfect for brightening your day.",
    rating: 5,
    reviews: 20,
    sku: "CUP-HLD-SM-04",
    tags: ["Eco-Friendly", "Fun", "Colorful"],
    detailedDescription: "The modern and youthful design makes it a trendy accessory for urban lifestyles and on-the-go routines.",
  },
  {
    id: 5,
    name: "Canvas Tote - White",
    price: "$25.00",
    priceRange: "$25.00 - $35.00",
    image: "/white-canvas-tote-bag.jpg",
    category: "Canvas Tote",
    description: "Spacious white canvas tote bag for all your daily essentials.",
    rating: 5,
    reviews: 18,
    sku: "TTE-WHT-05",
    tags: ["Eco-Friendly", "Spacious", "Minimalist"],
    detailedDescription: "Durable canvas material with reinforced handles, perfect for shopping, work, or casual outings.",
  },
  {
    id: 6,
    name: "Canvas Tote - Black",
    price: "$25.00",
    priceRange: "$25.00 - $35.00",
    image: "/black-canvas-tote-bag.jpg",
    category: "Canvas Tote",
    description: "Classic black canvas tote with timeless design.",
    rating: 5,
    reviews: 22,
    sku: "TTE-BLK-06",
    tags: ["Eco-Friendly", "Classic", "Versatile"],
    detailedDescription: "Perfect for any occasion, this black tote complements any outfit while being environmentally conscious.",
  },
  {
    id: 7,
    name: "Canvas Tote - Brown",
    price: "$25.00",
    priceRange: "$25.00 - $35.00",
    image: "/brown-canvas-tote-bag.jpg",
    category: "Canvas Tote",
    description: "Earthy brown canvas tote with natural aesthetic.",
    rating: 5,
    reviews: 14,
    sku: "TTE-BRN-07",
    tags: ["Eco-Friendly", "Natural", "Stylish"],
    detailedDescription: "Made from sustainable materials with a focus on durability and style.",
  },
  {
    id: 8,
    name: "Canvas Tote - Embroidered",
    price: "$35.00",
    priceRange: "$35.00 - $45.00",
    image: "/white-canvas-tote-bag-with-floral-embroidery.jpg",
    category: "Canvas Tote",
    description: "Beautiful floral embroidery on premium canvas.",
    rating: 5,
    reviews: 25,
    sku: "TTE-EMB-08",
    tags: ["Eco-Friendly", "Embroidered", "Premium"],
    detailedDescription: "Hand-embroidered details make each bag unique and special.",
  },
  {
    id: 9,
    name: "Cosmetic Bag - White",
    price: "$12.00",
    priceRange: "$12.00 - $18.00",
    image: "/white-cosmetic-pouch-bag.jpg",
    category: "Cosmetic Bag",
    description: "Compact white cosmetic bag for your beauty essentials.",
    rating: 5,
    reviews: 16,
    sku: "CSM-WHT-09",
    tags: ["Compact", "Practical", "Clean"],
    detailedDescription: "Perfect size for makeup, skincare, or travel toiletries with easy-access zipper.",
  },
  {
    id: 10,
    name: "Cosmetic Bag - Black",
    price: "$12.00",
    priceRange: "$12.00 - $18.00",
    image: "/black-cosmetic-bag-with-zipper.jpg",
    category: "Cosmetic Bag",
    description: "Sleek black cosmetic bag with durable zipper.",
    rating: 5,
    reviews: 19,
    sku: "CSM-BLK-10",
    tags: ["Sleek", "Durable", "Practical"],
    detailedDescription: "Water-resistant fabric keeps your items safe and organized.",
  },
  {
    id: 11,
    name: "Pen Case - Black",
    price: "$10.00",
    priceRange: "$10.00 - $15.00",
    image: "/black-pen-case-with-zipper.jpg",
    category: "Pen Case",
    description: "Minimalist black pen case for students and professionals.",
    rating: 5,
    reviews: 11,
    sku: "PEN-BLK-11",
    tags: ["Minimalist", "Student", "Professional"],
    detailedDescription: "Holds multiple pens, pencils, and small accessories with secure zipper closure.",
  },
  {
    id: 12,
    name: "Pen Case - White",
    price: "$10.00",
    priceRange: "$10.00 - $15.00",
    image: "/white-pen-case.jpg",
    category: "Pen Case",
    description: "Clean white pen case with ample storage space.",
    rating: 5,
    reviews: 9,
    sku: "PEN-WHT-12",
    tags: ["Clean", "Spacious", "Simple"],
    detailedDescription: "Made from durable fabric that's easy to clean and maintain.",
  },
  {
    id: 13,
    name: "Cup Holder - Pink/Sakura",
    price: "$18.00",
    priceRange: "$18.00 - $28.00",
    image: "/pink-sakura-cup-holder-with-white-tag-on-wooden-su.jpg",
    category: "Cup Holder",
    description: "Beautiful sakura-themed pink cup holder.",
    rating: 5,
    reviews: 17,
    sku: "CUP-HLD-SK-13",
    tags: ["Eco-Friendly", "Floral", "Elegant"],
    detailedDescription: "Delicate sakura pattern perfect for spring and cherry blossom lovers.",
  },
];

export const categories = ["All", "Cup Holder", "Canvas Tote", "Cosmetic Bag", "Pen Case"];
