export interface Product {
  id: number;
  name: string;
  price: string;
  priceRange?: string;
  image: string;
  category: string;
  description: string;
  rating: number;
  reviews: number;
  sku: string;
  tags: string[];
  detailedDescription?: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Cup Holder - PreMade",
    price: "15.000đ",
    priceRange: "15.000đ - 25.000đ",
    image: "/white-cup-holder-with-plant-and-teddy-bear.jpg",
    category: "Túi đựng ly",
    description: "Túi đựng ly thân thiện với môi trường, có thể tái sử dụng làm từ vải bền — hoàn hảo cho đồ uống hàng ngày của bạn và lối sống bền vững.",
    rating: 5,
    reviews: 12,
    sku: "CUP-HLD-PM-01",
    tags: ["Thân thiện môi trường", "Có sẵn", "Cá nhân hóa"],
    detailedDescription: "Túi đựng ly là người bạn đồng hành lý tưởng cho những người có ý thức về môi trường, yêu thích cà phê, trà sữa hoặc sinh tố hàng ngày nhưng muốn giảm dấu chân sinh thái của mình. Được thiết kế để thay thế túi nhựa và giá đỡ dùng một lần, túi vải này thúc đẩy sự bền vững mà không ảnh hưởng đến phong cách hay sự tiện lợi.",
  },
  {
    id: 2,
    name: "Cup Holder - Red/White",
    price: "18.000đ",
    priceRange: "18.000đ - 28.000đ",
    image: "/red-and-white-cup-holders-with-straps.jpg",
    category: "Túi đựng ly",
    description: "Túi đựng ly màu đỏ trắng thời trang với dây đeo có thể điều chỉnh cho mọi kích cỡ ly.",
    rating: 5,
    reviews: 8,
    sku: "CUP-HLD-RW-02",
    tags: ["Thân thiện môi trường", "Nhiều màu sắc", "Có thể điều chỉnh"],
    detailedDescription: "Được làm từ vật liệu thân thiện với môi trường chất lượng cao, túi đựng ly này bền, có thể giặt được và dễ dàng gấp lại để mang theo trong túi xách hoặc túi của bạn.",
  },
  {
    id: 3,
    name: "Cup Holder - Br/Wh",
    price: "20.000đ",
    priceRange: "20.000đ - 30.000đ",
    image: "/brown-and-white-cup-holder-with-strap.jpg",
    category: "Túi đựng ly",
    description: "Thiết kế nâu trắng cổ điển với chất lượng vải cao cấp.",
    rating: 5,
    reviews: 15,
    sku: "CUP-HLD-BW-03",
    tags: ["Thân thiện môi trường", "Cổ điển", "Cao cấp"],
    detailedDescription: "Điều khiến nó thực sự đặc biệt là tùy chọn cá nhân hóa: thêu tên, chữ cái đầu hoặc biểu tượng yêu thích của bạn để tạo ra một thiết kế độc nhất vô nhị.",
  },
  {
    id: 4,
    name: "Cup Holder - Smiley",
    price: "15.000đ",
    priceRange: "15.000đ - 25.000đ",
    image: "/colorful-cup-holders-with-smiley-face-and-coffee-d.jpg",
    category: "Túi đựng ly",
    description: "Thiết kế mặt cười vui nhộn hoàn hảo để làm sáng ngày của bạn.",
    rating: 5,
    reviews: 20,
    sku: "CUP-HLD-SM-04",
    tags: ["Thân thiện môi trường", "Vui nhộn", "Nhiều màu sắc"],
    detailedDescription: "Thiết kế hiện đại và trẻ trung khiến nó trở thành phụ kiện thời trang cho lối sống đô thị và sinh hoạt di động.",
  },
  {
    id: 5,
    name: "Canvas Tote - White",
    price: "25.000đ",
    priceRange: "25.000đ - 35.000đ",
    image: "/white-canvas-tote-bag.jpg",
    category: "Túi Tote",
    description: "Túi tote vải canvas màu trắng rộng rãi cho tất cả các vật dụng hàng ngày của bạn.",
    rating: 5,
    reviews: 18,
    sku: "TTE-WHT-05",
    tags: ["Thân thiện môi trường", "Rộng rãi", "Tối giản"],
    detailedDescription: "Vật liệu canvas bền với quai được gia cố, hoàn hảo cho việc mua sắm, làm việc hoặc đi chơi thường ngày.",
  },
  {
    id: 6,
    name: "Canvas Tote - Black",
    price: "25.000đ",
    priceRange: "25.000đ - 35.000đ",
    image: "/black-canvas-tote-bag.jpg",
    category: "Túi Tote",
    description: "Túi tote canvas màu đen cổ điển với thiết kế vượt thời gian.",
    rating: 5,
    reviews: 22,
    sku: "TTE-BLK-06",
    tags: ["Thân thiện môi trường", "Cổ điển", "Đa năng"],
    detailedDescription: "Hoàn hảo cho mọi dịp, túi tote màu đen này bổ sung cho bất kỳ trang phục nào trong khi vẫn thân thiện với môi trường.",
  },
  {
    id: 7,
    name: "Canvas Tote - Brown",
    price: "25.000đ",
    priceRange: "25.000đ - 35.000đ",
    image: "/brown-canvas-tote-bag.jpg",
    category: "Túi Tote",
    description: "Túi tote canvas màu nâu đất với thẩm mỹ tự nhiên.",
    rating: 5,
    reviews: 14,
    sku: "TTE-BRN-07",
    tags: ["Thân thiện môi trường", "Tự nhiên", "Thời trang"],
    detailedDescription: "Được làm từ vật liệu bền vững với trọng tâm vào độ bền và phong cách.",
  },
  {
    id: 8,
    name: "Canvas Tote - Embroidered",
    price: "35.000đ",
    priceRange: "35.000đ - 45.000đ",
    image: "/white-canvas-tote-bag-with-floral-embroidery.jpg",
    category: "Túi Tote",
    description: "Thêu hoa đẹp trên canvas cao cấp.",
    rating: 5,
    reviews: 25,
    sku: "TTE-EMB-08",
    tags: ["Thân thiện môi trường", "Được thêu", "Cao cấp"],
    detailedDescription: "Chi tiết thêu tay làm cho mỗi chiếc túi trở nên độc đáo và đặc biệt.",
  },
  {
    id: 9,
    name: "Cosmetic Bag - White",
    price: "12.000đ",
    priceRange: "12.000đ - 18.000đ",
    image: "/white-cosmetic-pouch-bag.jpg",
    category: "Túi đựng mỹ phẩm",
    description: "Túi đựng mỹ phẩm màu trắng nhỏ gọn cho các vật dụng làm đẹp thiết yếu của bạn.",
    rating: 5,
    reviews: 16,
    sku: "CSM-WHT-09",
    tags: ["Nhỏ gọn", "Thực tế", "Sạch sẽ"],
    detailedDescription: "Kích thước hoàn hảo cho trang điểm, chăm sóc da hoặc đồ vệ sinh du lịch với khóa kéo dễ sử dụng.",
  },
  {
    id: 10,
    name: "Cosmetic Bag - Black",
    price: "12.000đ",
    priceRange: "12.000đ - 18.000đ",
    image: "/black-cosmetic-bag-with-zipper.jpg",
    category: "Túi đựng mỹ phẩm",
    description: "Túi đựng mỹ phẩm màu đen thanh lịch với khóa kéo bền.",
    rating: 5,
    reviews: 19,
    sku: "CSM-BLK-10",
    tags: ["Thanh lịch", "Bền", "Thực tế"],
    detailedDescription: "Vải chống thấm nước giữ cho các vật dụng của bạn an toàn và được tổ chức.",
  },
  {
    id: 11,
    name: "Pen Case - Black",
    price: "10.000đ",
    priceRange: "10.000đ - 15.000đ",
    image: "/black-pen-case-with-zipper.jpg",
    category: "Hộp bút",
    description: "Hộp bút màu đen tối giản cho học sinh và chuyên gia.",
    rating: 5,
    reviews: 11,
    sku: "PEN-BLK-11",
    tags: ["Tối giản", "Học sinh", "Chuyên nghiệp"],
    detailedDescription: "Chứa nhiều bút, bút chì và phụ kiện nhỏ với khóa kéo an toàn.",
  },
  {
    id: 12,
    name: "Pen Case - White",
    price: "10.000đ",
    priceRange: "10.000đ - 15.000đ",
    image: "/white-pen-case.jpg",
    category: "Hộp bút",
    description: "Hộp bút màu trắng sạch sẽ với không gian lưu trữ rộng rãi.",
    rating: 5,
    reviews: 9,
    sku: "PEN-WHT-12",
    tags: ["Sạch sẽ", "Rộng rãi", "Đơn giản"],
    detailedDescription: "Được làm từ vải bền dễ dàng làm sạch và bảo trì.",
  },
  {
    id: 13,
    name: "Cup Holder - Pink/Sakura",
    price: "18.000đ",
    priceRange: "18.000đ - 28.000đ",
    image: "/pink-sakura-cup-holder-with-white-tag-on-wooden-su.jpg",
    category: "Túi đựng ly",
    description: "Túi đựng ly màu hồng với chủ đề hoa anh đào xinh đẹp.",
    rating: 5,
    reviews: 17,
    sku: "CUP-HLD-SK-13",
    tags: ["Thân thiện môi trường", "Hoa", "Thanh lịch"],
    detailedDescription: "Họa tiết hoa anh đào tinh tế hoàn hảo cho mùa xuân và những người yêu thích hoa anh đào.",
  },
];

export const categories = ["Tất cả", "Túi đựng ly", "Túi Tote", "Túi đựng mỹ phẩm", "Hộp bút"];
